#!/bin/bash
# =============================================================================
# Label Studio Installation Script for Google Cloud Workstations
# Version: 2.1.4 (2026-03-25)
# =============================================================================
# Installs Label Studio with persistent configuration for Cloud Workstations.
# Handles auto-start on reboot, and management commands.
# =============================================================================
SCRIPT_VERSION="2.1.4"

echo "=============================================="
echo "Label Studio Installer v${SCRIPT_VERSION}"
echo "=============================================="
echo ""

# Detect the actual user (not root even when using sudo)
ACTUAL_USER="${SUDO_USER:-$USER}"
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)

echo "Detected user: $ACTUAL_USER"
echo "Home directory: $ACTUAL_HOME"

# Fix common apt repository issues before proceeding
echo "[Step 1/10] Checking apt repositories..."
apt_output=$(sudo apt-get update 2>&1 || true)
if echo "$apt_output" | grep -q "NO_PUBKEY\|not signed"; then
    echo "  Warning: Some apt repositories have GPG key issues. Won't affect Label Studio."
fi
echo "  ✓ apt update done"

# Check Python version (Label Studio requires >= 3.10)
echo "[Step 2/10] Checking Python version..."
PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo "0.0")
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)
if [ "$PYTHON_MAJOR" -lt 3 ] || { [ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 10 ]; }; then
    echo "Warning: Python $PYTHON_VERSION detected. Label Studio requires Python >= 3.10."
    echo "Attempting to install Python 3.12..."
    sudo apt-get install -y python3.12 python3.12-venv python3.12-dev || true
    # Use python3.12 if available
    if command -v python3.12 &>/dev/null; then
        PYTHON_BIN="python3.12"
    else
        echo "Warning: Could not install Python 3.12, continuing with $PYTHON_VERSION"
        PYTHON_BIN="python3"
    fi
else
    PYTHON_BIN="python3"
    echo "✓ Python $PYTHON_VERSION detected"
fi

# Install Python3 and pip if not already installed
echo "[Step 3/10] Installing Python dependencies..."
sudo apt-get install -y python3 python3-pip python3-venv || {
    echo "  ERROR: Failed to install Python dependencies"
    exit 1
}

# Create a persistent directory for Label Studio in the user's home
LABEL_STUDIO_HOME="$ACTUAL_HOME/.label-studio"
echo "[Step 4/10] Creating Label Studio directory at: $LABEL_STUDIO_HOME"
sudo -u "$ACTUAL_USER" mkdir -p "$LABEL_STUDIO_HOME"

# Create a virtual environment for Label Studio
if [ ! -d "$LABEL_STUDIO_HOME/venv" ]; then
    echo "[Step 5/10] Creating Python virtual environment (using $PYTHON_BIN)..."
    sudo -u "$ACTUAL_USER" $PYTHON_BIN -m venv "$LABEL_STUDIO_HOME/venv" || {
        echo "  ERROR: Failed to create virtual environment"
        exit 1
    }
else
    echo "[Step 5/10] Virtual environment already exists, skipping."
fi

# Activate the virtual environment and install Label Studio
echo "[Step 6/10] Installing Label Studio in virtual environment..."
sudo -u "$ACTUAL_USER" bash << EOFVENV
source "$LABEL_STUDIO_HOME/venv/bin/activate"
pip install --upgrade pip
pip install label-studio
EOFVENV

# Verify installation
if [ ! -f "$LABEL_STUDIO_HOME/venv/bin/label-studio" ]; then
    echo "Error: Label Studio installation failed"
    exit 1
fi
echo "  ✓ Label Studio installed successfully"

# Get version using pip show (NOT label-studio --version which starts Django!)
LS_VERSION=$(sudo -u "$ACTUAL_USER" bash -c "source '$LABEL_STUDIO_HOME/venv/bin/activate' && pip show label-studio 2>/dev/null" | grep -i '^Version:' | sed -E 's/Version: *//i' || echo "unknown")
if [ -z "$LS_VERSION" ]; then
    LS_VERSION="unknown"
fi
echo "  ✓ Label Studio version: $LS_VERSION"

# Write environment config file for Cloud Workstation proxy compatibility
echo "[Step 7/10] Writing environment config..."

# IMPORTANT: Label Studio reads .env from its BASE_DATA_DIR, which defaults to
# ~/.local/share/label-studio/ on Linux. We write .env to BOTH our directory
# AND Label Studio's default data directory so env vars are always loaded.
LS_DATA_DIR="$ACTUAL_HOME/.local/share/label-studio"
sudo -u "$ACTUAL_USER" mkdir -p "$LS_DATA_DIR"
sudo -u "$ACTUAL_USER" mkdir -p "$LABEL_STUDIO_HOME/data"

cat > "$LABEL_STUDIO_HOME/.env" << ENVEOF
# Label Studio config - generated by install_label_studio.sh v${SCRIPT_VERSION}
# LABEL_STUDIO_HOST and CSRF_TRUSTED_ORIGINS are set at boot by startup.sh

# Disable CSRF (Cloud Workstations uses IAM authentication)
USE_ENFORCE_CSRF_CHECKS=0

# Use stable features only
EXPERIMENTAL_FEATURES=0

# Trust proxy headers
USE_X_FORWARDED_HOST=true
USE_X_FORWARDED_PORT=true
SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https

# Local file serving
LOCAL_FILES_SERVING_ENABLED=true
LOCAL_FILES_DOCUMENT_ROOT=${LABEL_STUDIO_HOME}/data

LOG_LEVEL=WARNING
ENVEOF
chown "$ACTUAL_USER:$ACTUAL_USER" "$LABEL_STUDIO_HOME/.env"
echo "✓ Environment config written to $LABEL_STUDIO_HOME/.env"

# Copy to Label Studio's data directory
cp "$LABEL_STUDIO_HOME/.env" "$LS_DATA_DIR/.env"
chown "$ACTUAL_USER:$ACTUAL_USER" "$LS_DATA_DIR/.env"
echo "✓ Environment config also written to $LS_DATA_DIR/.env"

# Verify .env was written to both locations
if [ ! -f "$LABEL_STUDIO_HOME/.env" ] || [ ! -f "$LS_DATA_DIR/.env" ]; then
    echo "Error: Failed to write .env file(s)"
    exit 1
fi

# ============================================================
# PERSISTENCE SETUP
# ============================================================
echo "[Step 8/10] Setting up persistence (PATH, auto-start)..."

# Create directories
LOCAL_BIN="$ACTUAL_HOME/.local/bin"
sudo -u "$ACTUAL_USER" mkdir -p "$LOCAL_BIN"

# Add ~/.local/bin to PATH if not already present
BASHRC="$ACTUAL_HOME/.bashrc"
if ! grep -q 'export PATH=.*\.local/bin' "$BASHRC" 2>/dev/null; then
    echo "Adding ~/.local/bin to PATH in .bashrc..."
    sudo -u "$ACTUAL_USER" bash -c "echo '' >> '$BASHRC'"
    sudo -u "$ACTUAL_USER" bash -c "echo '# Label Studio management commands' >> '$BASHRC'"
    sudo -u "$ACTUAL_USER" bash -c "echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> '$BASHRC'"
fi

# Clean old autostart blocks and add fresh one
sudo -u "$ACTUAL_USER" bash -c "
    sed -i '/Auto-start Label Studio/,/label-studio-autostart/d' '$BASHRC'
    sed -i '/Starting Label Studio in background/d' '$BASHRC'
    sed -i '/^1$/d' '$BASHRC'
" 2>/dev/null || true

sudo -u "$ACTUAL_USER" bash -c "cat >> '$BASHRC'" << 'BASHRC_EOF'

# Auto-start Label Studio (only for interactive shells)
if [[ $- == *i* ]] && [ -t 0 ]; then
    if [ -f "$HOME/.label-studio/startup.sh" ] && ! pgrep -f "label-studio start" > /dev/null 2>&1; then
        # Suppress output to avoid SSH issues, log to file instead
        (nohup "$HOME/.label-studio/startup.sh" >> "$HOME/.label-studio/autostart.log" 2>&1 &) &>/dev/null
        # Delayed message so it doesn't interfere with SSH handshake
        (sleep 2 && echo "Label Studio started in background." >> "$HOME/.label-studio/autostart.log") &>/dev/null &
    fi
fi
# label-studio-autostart marker
BASHRC_EOF

echo "Creating startup script..."

# Create the PERSISTENT startup script in ~/.label-studio/
sudo -u "$ACTUAL_USER" bash -c "cat > '$LABEL_STUDIO_HOME/startup.sh'" << 'EOF'
#!/bin/bash
# Label Studio startup script (persists across restarts)

# Detect the actual user
ACTUAL_USER="${SUDO_USER:-$USER}"
if [ "$ACTUAL_USER" = "root" ]; then
    # Find the first non-root user with a home directory
    ACTUAL_USER=$(awk -F: '$3>=1000 && $3<60000 && $1!="nobody" {print $1; exit}' /etc/passwd)
fi
ACTUAL_HOME=$(eval echo ~$ACTUAL_USER)

LABEL_STUDIO_HOME="$ACTUAL_HOME/.label-studio"
LOG_FILE="$LABEL_STUDIO_HOME/label-studio.log"
ENV_FILE="$LABEL_STUDIO_HOME/.env"
RUNTIME_ENV_FILE="$LABEL_STUDIO_HOME/.env.runtime"

# Ensure the directory exists
mkdir -p "$LABEL_STUDIO_HOME"
mkdir -p "$LABEL_STUDIO_HOME/data"

# Fix log file ownership (may have been created by root in previous run)
touch "$LOG_FILE"
chown "$ACTUAL_USER" "$LOG_FILE" 2>/dev/null || true
chown "$ACTUAL_USER" "$LABEL_STUDIO_HOME" 2>/dev/null || true

# Timestamp for log clarity
echo "" | tee -a "$LOG_FILE"
echo "=== Startup at $(date '+%Y-%m-%d %H:%M:%S %Z') ===" | tee -a "$LOG_FILE"

# Check if Label Studio is already running
if pgrep -f "label-studio start" > /dev/null; then
    echo "Label Studio is already running (PID: $(pgrep -f 'label-studio start'))." | tee -a "$LOG_FILE"
    exit 0
fi

# Detect Cloud Workstation URL
WS_NAME=$(hostname 2>/dev/null | tr -d '\n' || echo "")
CLUSTER_DOMAIN=""

# Method 1: DNS search domains
if [ -f /etc/resolv.conf ]; then
    CLUSTER_DOMAIN=$(grep -E '^search|^domain' /etc/resolv.conf 2>/dev/null \
        | grep -oE '[a-z0-9-]+\.cloudworkstations\.dev' \
        | head -1 || echo "")
fi

# Method 2: Try GCP metadata server custom attributes
if [ -z "$CLUSTER_DOMAIN" ]; then
    for attr in cluster-hostname workstation-cluster-domain workstation-cluster; do
        ATTR_VAL=$(curl -sf -m 2 -H 'Metadata-Flavor: Google' \
            "http://metadata.google.internal/computeMetadata/v1/instance/attributes/$attr" \
            2>/dev/null || echo "")
        if echo "$ATTR_VAL" | grep -q 'cloudworkstations\.dev'; then
            CLUSTER_DOMAIN=$(echo "$ATTR_VAL" | grep -oE '[a-z0-9.-]+\.cloudworkstations\.dev' | head -1)
            break
        fi
    done
fi

# Method 3: Full resolv.conf search
if [ -z "$CLUSTER_DOMAIN" ] && [ -f /etc/resolv.conf ]; then
    CLUSTER_DOMAIN=$(cat /etc/resolv.conf 2>/dev/null \
        | tr ' ' '\n' \
        | grep 'cloudworkstations\.dev' \
        | head -1 || echo "")
fi

# Method 4: GCE metadata proxy-url
if [ -z "$CLUSTER_DOMAIN" ]; then
    PROXY_URL=$(curl -sf -m 2 -H 'Metadata-Flavor: Google' \
        "http://metadata.google.internal/computeMetadata/v1/instance/attributes/proxy-url" \
        2>/dev/null || echo "")
    if echo "$PROXY_URL" | grep -q 'cloudworkstations\.dev'; then
        CLUSTER_DOMAIN=$(echo "$PROXY_URL" | grep -oE '[a-z0-9.-]+\.cloudworkstations\.dev' | head -1)
    fi
fi

# Build runtime config
if [ -n "$CLUSTER_DOMAIN" ] && [ -n "$WS_NAME" ]; then
    WS_URL="https://8080-${WS_NAME}.${CLUSTER_DOMAIN}"
    echo "Detected Cloud Workstation URL: $WS_URL" | tee -a "$LOG_FILE"
    cat > "$RUNTIME_ENV_FILE" << DYNEOF
# Runtime config (regenerated on boot)
LABEL_STUDIO_HOST=${WS_URL}
CSRF_TRUSTED_ORIGINS=${WS_URL},https://*.cloudworkstations.dev
DYNEOF
elif [ -f "$LABEL_STUDIO_HOME/.env.custom" ]; then
    # Prefer manually configured URL (set via label-studio-set-url)
    cp "$LABEL_STUDIO_HOME/.env.custom" "$RUNTIME_ENV_FILE"
    echo "Using manually configured URL from .env.custom" | tee -a "$LOG_FILE"
else
    # Fallback: wildcard CSRF origins
    cat > "$RUNTIME_ENV_FILE" << DYNEOF
# Runtime config (URL not detected)
CSRF_TRUSTED_ORIGINS=https://*.cloudworkstations.dev
DYNEOF
    echo "Note: Could not auto-detect Cloud Workstation URL." | tee -a "$LOG_FILE"
    echo "      Run 'label-studio-set-url https://PORT-HOST.CLUSTER.cloudworkstations.dev' if login fails." | tee -a "$LOG_FILE"
fi
chown "$ACTUAL_USER" "$RUNTIME_ENV_FILE" 2>/dev/null || true

# Merge config to Label Studio data directory
LS_DATA_DIR="$ACTUAL_HOME/.local/share/label-studio"
mkdir -p "$LS_DATA_DIR"
cat "$ENV_FILE" > "$LS_DATA_DIR/.env" 2>/dev/null || true
echo "" >> "$LS_DATA_DIR/.env"
cat "$RUNTIME_ENV_FILE" >> "$LS_DATA_DIR/.env" 2>/dev/null || true
chown "$ACTUAL_USER" "$LS_DATA_DIR/.env" 2>/dev/null || true
echo "Environment merged to $LS_DATA_DIR/.env" | tee -a "$LOG_FILE"

# Start Label Studio as a background service
echo "Starting Label Studio..." | tee -a "$LOG_FILE"
cd "$LABEL_STUDIO_HOME"

# Load environment variables
if [ -f "$ENV_FILE" ]; then
    set -a
    source "$ENV_FILE"
    set +a
fi
if [ -f "$RUNTIME_ENV_FILE" ]; then
    set -a
    source "$RUNTIME_ENV_FILE"
    set +a
fi

# Launch Label Studio
CURRENT_USER=$(whoami)
if [ "$CURRENT_USER" = "$ACTUAL_USER" ]; then
    nohup "$LABEL_STUDIO_HOME/venv/bin/label-studio" start \
        --host 0.0.0.0 \
        --port 8080 \
        --data-dir "$LABEL_STUDIO_HOME/data" \
        --no-browser \
        --log-level WARNING \
        >> "$LOG_FILE" 2>&1 &
    echo $! > "$LABEL_STUDIO_HOME/label-studio.pid"
else
    su - "$ACTUAL_USER" -c "
        cd '$LABEL_STUDIO_HOME'
        set -a
        [ -f '$ENV_FILE' ] && source '$ENV_FILE'
        [ -f '$RUNTIME_ENV_FILE' ] && source '$RUNTIME_ENV_FILE'
        set +a
        nohup '$LABEL_STUDIO_HOME/venv/bin/label-studio' start \
            --host 0.0.0.0 --port 8080 \
            --data-dir '$LABEL_STUDIO_HOME/data' \
            --no-browser --log-level WARNING \
            >> '$LOG_FILE' 2>&1 &
        echo \$! > '$LABEL_STUDIO_HOME/label-studio.pid'
    "
fi

echo "Label Studio started." | tee -a "$LOG_FILE"
echo "Access at: http://localhost:8080" | tee -a "$LOG_FILE"
echo "Logs: $LOG_FILE"
EOF

# Make the persistent startup script executable
chmod +x "$LABEL_STUDIO_HOME/startup.sh"
chown "$ACTUAL_USER:$ACTUAL_USER" "$LABEL_STUDIO_HOME/startup.sh"

# Create startup.d bootstrap
STARTUP_SCRIPT="/etc/workstation-startup.d/50-start-label-studio"
if [ -d "/etc/workstation-startup.d" ]; then
    sudo bash -c "cat > '$STARTUP_SCRIPT'" << BOOTSTRAP_EOF
#!/bin/bash
set -euo pipefail

LOG_FILE="/var/log/label-studio-bootstrap.log"
echo "=== label-studio bootstrap \\$(date '+%Y-%m-%d %H:%M:%S %Z') ===" >> "\$LOG_FILE"

ACTUAL_USER=\$(awk -F: '\$3>=1000 && \$3<60000 && \$1!="nobody" {print \$1; exit}' /etc/passwd)
if [ -z "\${ACTUAL_USER:-}" ]; then
    echo "No non-root user found; skipping startup" >> "\$LOG_FILE"
    exit 0
fi

ACTUAL_HOME=\$(eval echo ~\$ACTUAL_USER)
START_SCRIPT="\$ACTUAL_HOME/.label-studio/startup.sh"

# Home mount can come up a little late; wait up to 2 minutes for startup script.
for i in \$(seq 1 24); do
    if [ -x "\$START_SCRIPT" ]; then
        break
    fi
    sleep 5
done

if [ ! -x "\$START_SCRIPT" ]; then
    echo "startup.sh not found/executable at \$START_SCRIPT" >> "\$LOG_FILE"
    exit 0
fi

if pgrep -f "label-studio start" >/dev/null 2>&1; then
    echo "Label Studio already running; nothing to do" >> "\$LOG_FILE"
    exit 0
fi

echo "Starting Label Studio as user: \$ACTUAL_USER" >> "\$LOG_FILE"
if command -v runuser >/dev/null 2>&1; then
    runuser -u "\$ACTUAL_USER" -- bash -lc "nohup '\$START_SCRIPT' >> '\$ACTUAL_HOME/.label-studio/autostart.log' 2>&1 &"
else
    su - "\$ACTUAL_USER" -c "nohup '\$START_SCRIPT' >> '\$ACTUAL_HOME/.label-studio/autostart.log' 2>&1 &"
fi

# Quick readiness probe (best-effort)
for i in \$(seq 1 18); do
    HTTP_CODE=\$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 2>/dev/null || true)
    if echo "\$HTTP_CODE" | grep -q "200\\|302"; then
        echo "Label Studio is reachable on localhost:8080" >> "\$LOG_FILE"
        exit 0
    fi
    sleep 5
done

echo "Label Studio started but readiness check timed out" >> "\$LOG_FILE"
BOOTSTRAP_EOF
    sudo chmod +x "$STARTUP_SCRIPT"
fi

# Create management commands
echo "[Step 9/10] Creating management commands in ~/.local/bin/..."

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-status'" << 'EOF'
#!/bin/bash
LABEL_STUDIO_HOME="$HOME/.label-studio"

if pgrep -f "label-studio start" > /dev/null; then
    VERSION=$("$LABEL_STUDIO_HOME/venv/bin/pip" show label-studio 2>/dev/null | grep -i '^Version:' | sed 's/Version: *//')
    [ -z "$VERSION" ] && VERSION="unknown"
    echo "✓ Label Studio is running"
    echo "  PID:     $(pgrep -f 'label-studio start')"
    echo "  Version: $VERSION"
    echo "  URL:     http://localhost:8080"
    echo "  Logs:    $LABEL_STUDIO_HOME/label-studio.log"
else
    echo "✗ Label Studio is not running"
    echo "  Start with: label-studio-restart"
fi
EOF
chmod +x "$LOCAL_BIN/label-studio-status"

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-restart'" << 'EOF'
#!/bin/bash
LABEL_STUDIO_HOME="$HOME/.label-studio"

echo "Stopping Label Studio..."
pkill -f "label-studio start" || true
sleep 3
echo "Starting Label Studio..."
"$LABEL_STUDIO_HOME/startup.sh"
echo "Waiting for Label Studio to be ready..."
for i in $(seq 1 18); do
    sleep 10
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 2>/dev/null)
    if echo "$HTTP_CODE" | grep -q "200\|302"; then
        echo "✓ Label Studio is ready at http://localhost:8080"
        exit 0
    fi
    echo "  Still starting... ($((i * 10))s)"
done
echo "Label Studio is taking longer than expected. Check logs with: label-studio-logs"
EOF
chmod +x "$LOCAL_BIN/label-studio-restart"

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-stop'" << 'EOF'
#!/bin/bash
if pgrep -f "label-studio start" > /dev/null; then
    echo "Stopping Label Studio..."
    pkill -f "label-studio start"
    echo "✓ Label Studio stopped."
else
    echo "Label Studio is not running."
fi
EOF
chmod +x "$LOCAL_BIN/label-studio-stop"

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-logs'" << 'EOF'
#!/bin/bash
LOG_FILE="$HOME/.label-studio/label-studio.log"

if [ -f "$LOG_FILE" ]; then
    echo "=== Label Studio Logs ($LOG_FILE) ==="
    tail -f "$LOG_FILE"
else
    echo "Log file not found at: $LOG_FILE"
    echo "Label Studio may still be starting for the first time."
fi
EOF
chmod +x "$LOCAL_BIN/label-studio-logs"

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-update'" << 'EOF'
#!/bin/bash
LABEL_STUDIO_HOME="$HOME/.label-studio"

echo "Stopping Label Studio..."
pkill -f "label-studio start" || true
sleep 2

echo "Updating Label Studio..."
source "$LABEL_STUDIO_HOME/venv/bin/activate"
pip install --upgrade label-studio

echo "Restarting Label Studio..."
"$LABEL_STUDIO_HOME/startup.sh"
echo "✓ Update complete. Check version with: label-studio-status"
EOF
chmod +x "$LOCAL_BIN/label-studio-update"

# Set workstation URL for CSRF / proxy compatibility
sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-set-url'" << 'EOF'
#!/bin/bash
# Usage: label-studio-set-url https://8080-w-NAME.cluster-ID.cloudworkstations.dev
LABEL_STUDIO_HOME="$HOME/.label-studio"

if [ -z "$1" ]; then
    echo "Usage: label-studio-set-url https://PORT-HOST.CLUSTER.cloudworkstations.dev"
    echo ""
    echo "This sets the external URL Label Studio uses for CSRF and link generation."
    echo "Find your URL in the Cloud Workstations web console (port 8080 forwarding link)."
    echo ""
    if [ -f "$LABEL_STUDIO_HOME/.env.custom" ]; then
        echo "Current custom URL config:"
        cat "$LABEL_STUDIO_HOME/.env.custom"
    fi
    exit 1
fi

WS_URL="$1"
# Strip trailing slash
WS_URL="${WS_URL%/}"

if ! echo "$WS_URL" | grep -q '^https\?://'; then
    echo "Error: URL must start with http:// or https://"
    exit 1
fi

echo "Setting Label Studio external URL to: $WS_URL"
cat > "$LABEL_STUDIO_HOME/.env.custom" << CUSTOMEOF
# Custom URL config
LABEL_STUDIO_HOST=${WS_URL}
CSRF_TRUSTED_ORIGINS=${WS_URL},https://*.cloudworkstations.dev
CUSTOMEOF

echo "✓ URL saved to $LABEL_STUDIO_HOME/.env.custom"
echo "  Restarting Label Studio to apply..."
label-studio-restart
EOF
chmod +x "$LOCAL_BIN/label-studio-set-url"

# Write the installer version to a file so diagnostics can read it
echo "$SCRIPT_VERSION" > "$LABEL_STUDIO_HOME/.installer-version"
chown "$ACTUAL_USER:$ACTUAL_USER" "$LABEL_STUDIO_HOME/.installer-version"

sudo -u "$ACTUAL_USER" bash -c "cat > '$LOCAL_BIN/label-studio-diagnostics'" << 'EOF'
#!/bin/bash
LABEL_STUDIO_HOME="$HOME/.label-studio"

echo "=== Label Studio Diagnostics ==="
echo ""

INSTALLER_VER="unknown"
if [ -f "$LABEL_STUDIO_HOME/.installer-version" ]; then
    INSTALLER_VER=$(cat "$LABEL_STUDIO_HOME/.installer-version")
fi
LS_VER=$("$LABEL_STUDIO_HOME/venv/bin/pip" show label-studio 2>/dev/null | grep -i '^Version:' | sed 's/Version: *//')
[ -z "$LS_VER" ] && LS_VER="unknown"
echo "--- Versions ---"
echo "  Installer script: v${INSTALLER_VER}"
echo "  Label Studio:     v${LS_VER}"
echo ""

echo "--- Process ---"
if pgrep -f "label-studio start" > /dev/null; then
    echo "✓ Label Studio is RUNNING (PID: $(pgrep -f 'label-studio start'))"
else
    echo "✗ Label Studio is NOT running"
fi
echo ""
echo "--- HTTP Check ---"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 2>/dev/null)
echo "  localhost:8080 response: HTTP $HTTP_CODE"
echo ""
echo "--- Static config ($LABEL_STUDIO_HOME/.env) ---"
if [ -f "$LABEL_STUDIO_HOME/.env" ]; then
    grep -v '^#' "$LABEL_STUDIO_HOME/.env" | grep -v '^$'
else
    echo "  (not found)"
fi
echo ""
echo "--- Runtime config ($LABEL_STUDIO_HOME/.env.runtime) ---"
if [ -f "$LABEL_STUDIO_HOME/.env.runtime" ]; then
    grep -v '^#' "$LABEL_STUDIO_HOME/.env.runtime" | grep -v '^$'
else
    echo "  (not found — startup script may not have run yet)"
fi
echo ""
echo "--- Custom URL config ($LABEL_STUDIO_HOME/.env.custom) ---"
if [ -f "$LABEL_STUDIO_HOME/.env.custom" ]; then
    grep -v '^#' "$LABEL_STUDIO_HOME/.env.custom" | grep -v '^$'
else
    echo "  (not set — run 'label-studio-set-url https://YOUR-URL' if CSRF errors occur)"
fi
echo ""
echo "--- Hostname / DNS ---"
echo "  hostname:    $(hostname 2>/dev/null)"
echo "  DNS search:  $(grep -E '^search|^domain' /etc/resolv.conf 2>/dev/null | head -1 || echo '(not found)')"
CW_DOMAIN=$(grep -E '^search|^domain' /etc/resolv.conf 2>/dev/null \
    | grep -oE '[a-z0-9-]+\.cloudworkstations\.dev' | head -1 || echo "")
if [ -n "$CW_DOMAIN" ]; then
    echo "  Cloud Workstation domain: $CW_DOMAIN"
    echo "  ✓ Expected URL: https://8080-$(hostname).${CW_DOMAIN}"
else
    echo "  ✗ Could not detect Cloud Workstation domain from DNS"
    echo "    Manual fix: label-studio-set-url https://PORT-HOST.CLUSTER.cloudworkstations.dev"
fi
echo ""
echo "--- Recent log (last 10 lines) ---"
LOG_FILE="$LABEL_STUDIO_HOME/label-studio.log"
if [ -f "$LOG_FILE" ]; then
    tail -10 "$LOG_FILE"
else
    echo "  (log file not found)"
fi
EOF
chmod +x "$LOCAL_BIN/label-studio-diagnostics"

# Ensure all commands are owned by the user
chown -R "$ACTUAL_USER:$ACTUAL_USER" "$LOCAL_BIN"

echo ""
echo "=============================================="
echo "✓ Label Studio installation complete!"
echo "  Installer version: ${SCRIPT_VERSION}"
echo "  Label Studio:      ${LS_VERSION}"
echo "=============================================="
echo ""
echo "All data is stored in: $LABEL_STUDIO_HOME"
echo "Commands are in:       $LOCAL_BIN (added to PATH)"
echo "Config file:          $LABEL_STUDIO_HOME/.env"
echo ""
echo "Available commands:"
echo "  label-studio-status       - Check if Label Studio is running"
echo "  label-studio-restart      - Restart Label Studio"
echo "  label-studio-stop         - Stop Label Studio"
echo "  label-studio-logs         - View Label Studio logs"
echo "  label-studio-update       - Update Label Studio to latest version"
echo "  label-studio-set-url URL  - Set your Cloud Workstation external URL"
echo "  label-studio-diagnostics  - Show config, detected URL, and connection info"
echo ""
echo "IMPORTANT — If you see a CSRF/403 error on login:"
echo "  The startup script auto-detects your workstation URL via DNS."
echo "  If it fails, set it manually after Label Studio starts:"
echo ""
echo "    label-studio-set-url https://8080-\$(hostname).YOUR-CLUSTER.cloudworkstations.dev"
echo ""
echo "  Run 'label-studio-diagnostics' to see what URL was detected."
echo ""
echo "NOTE: Commands persist across workstation restarts (stored in ~/.local/bin)."
echo "      To use commands in this terminal session, run: source ~/.bashrc"
echo ""

# Verify critical CSRF setting before starting
echo "Verifying configuration..."
if grep -q "USE_ENFORCE_CSRF_CHECKS=0" "$LABEL_STUDIO_HOME/.env"; then
    echo "✓ CSRF bypass configured"
else
    echo "⚠ Warning: USE_ENFORCE_CSRF_CHECKS not found in .env - CSRF errors may occur"
fi

echo ""
echo "[Step 10/10] Starting Label Studio now..."

# Fix ownership of all label-studio files (may have been created by root)
chown -R "$ACTUAL_USER:$ACTUAL_USER" "$LABEL_STUDIO_HOME" 2>/dev/null || true
chown -R "$ACTUAL_USER:$ACTUAL_USER" "$ACTUAL_HOME/.local/share/label-studio" 2>/dev/null || true

"$LABEL_STUDIO_HOME/startup.sh"
echo ""
echo "Waiting for Label Studio to initialize..."
echo "Note: First run may take 2-3 minutes while the database is set up."
echo ""

# Wait for Label Studio to be ready (first run needs longer due to DB migrations)
MAX_WAIT=180
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 2>/dev/null)
    if echo "$HTTP_CODE" | grep -q "200\|302"; then
        echo ""
        echo "✓ Label Studio is ready! ($WAITED seconds)"
        echo ""
        echo "Access Label Studio at: http://localhost:8080"
        echo "For Cloud Workstations, use your workstation's port 8080 URL."
        exit 0
    fi
    sleep 10
    WAITED=$((WAITED + 10))
    # Show log tail every 30 seconds to help debug
    if [ $((WAITED % 30)) -eq 0 ]; then
        LOG_FILE="$LABEL_STUDIO_HOME/label-studio.log"
        if [ -f "$LOG_FILE" ]; then
            echo "  --- Recent log output ---"
            tail -3 "$LOG_FILE"
            echo "  -------------------------"
        fi
    fi
    echo "  Still waiting... ($WAITED seconds)"
done

echo ""
echo "Label Studio is taking longer than expected to start."
echo ""
echo "Check the process:  ps aux | grep label-studio"
echo "Check status:       label-studio-status"
echo "Check logs:         label-studio-logs"
echo ""
echo "Once ready, access at: http://localhost:8080"
